### ISSUE TITLE
Add current MVP, Beta, and Final Milestones to Kanban

### ISSUE THREAD

**Issue by matthewjackswann** [NPCMS/ElementalExplorers#18]

**Comment by James-Millan** [comment]
Made the milestones, does this also include creating issues to achieve the milestones?

**Comment by matthewjackswann** [comment]
I think it would make sense. Even if we make sub issues about them. I think it would make it easier to see what is required for each milestone and how far off them we are. At the moment we are just adding issues to the milestones as we get round to developing them
