### ISSUE TITLE
Race / Gameplay Loop

### ISSUE THREAD

**Issue by matthewjackswann** [NPCMS/ElementalExplorers#21]

**Comment by James-Millan** [comment]
Requires loading all players into the scene at a designated start point. Having a countdown to start the race, players are frozen during this time. Include a finish line and update everyone else that the player has finished. Introduce a countdown for the rest to finish?

We need to decided if we are going to have waypoints / checkpoints and if they are visible or invisible to players. (e.g if they go wildly off course).  Also are we going to have a lap system or will it be a race to the finish line?
