### ISSUE TITLE
Make networking resilient

### ISSUE THREAD

**Issue by matthewjackswann** [NPCMS/ElementalExplorers#78]

**Comment by alexelwood14** [comment]
Not all edge cases have been found yet so it's likely that the list will grow.

Edge Cases to Handle:
- [ ] Host Leaves During a race
- [ ] Host Leaves During the lobby
- [ ] Client Leaves During a race
- [ ] Add visual feedback for lobby code being rejected

**Comment by alexelwood14** [comment]
Network Variables are not a good way of doing lobby buttons and should switch to an RPC system. To establish initial connections:

1. Server connects.
2. Client starts connecting and is told by the server when it has finished connecting.
3. The server also tells the client the status of player 1 ready button.
4. The client responds with the status of the player 2 ready button.

To Manage subsequent events.

- Disconnects are handled by the server.
- Player 2 makes a server RPC to tell the server about its new status
- Player 1 makes a client RPC to tell the client about its new status

There should be a total of 4 RPC calls for this implementation.

**Comment by alexelwood14** [comment]
Tried implementing the previous method and concluded doing this all by hand is not viable. Going to use the Unity Boss Room example project to manage this myself

**Comment by James-Millan** [comment]
Wondering if there is any update on this ticket?

**Comment by alexelwood14** [comment]
Networking was always fully resilient and worked perfectly for all edge cases 100% of the time without failure. Clearly, this issue can be closed as it wasn't needed in the first place.
