### ISSUE TITLE
Complete a Unity tutorial

### ISSUE THREAD

**Issue by matthewjackswann** [NPCMS/ElementalExplorers#8]
https://www.youtube.com/watch?v=j48LtUkZRjU&list=PLPV2KyIb3jR5QFsefuO2RlAgWEz6EvVi6

**Comment by alexelwood14** [comment]
I've finished the tutorial :)

**Comment by alexelwood14** [comment]
- [ ] James
- [x] Alex
- [ ] Imran
- [x] Swanny

**Comment by James-Millan** [comment]
All of us have done the tutorial, closing this issue now.
